spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/laomazi2006/spring-config-files
# 采用spring cloud bus 进行 事件、消息总线，用于在集群（例如，配置变化事件）中传播状态变化，可与Spring Cloud Config联合实现热部署。
# 目的为了刷新配置系统马上收到进行改变
# http://www.rabbitmq.com
# 当post http://192.168.100.86:8888/bus/refresh 会收到配置的发送通知
  rabbitmq:
    host: 192.168.100.249
    port: 5672
    username: config-server
    password: 888888
server:
  port: 8888
management:
  security:
    enabled: false


